# Generated by Django 5.0.6 on 2025-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_category_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Notification Type')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
